### ISSUE TITLE
Upstreaming or merging with k10temp?

### ISSUE THREAD

**Issue by shmerl** [ocerman/zenpower#10] opened 2019-09-13 18:32 UTC
Did you consider merging it with k10temp? There is no need to limit the later to temperature only.

**Comment by Venemo** [comment] 2019-09-26 11:13
I'd also be interested to hear the answer to this.

**Comment by Venemo** [comment] 2019-09-26 11:15
I guess this question might be a duplicate of #1

**Comment by ocerman** [comment] 2019-09-29 10:40
No plans currently as I cannot guarantee that this driver will work with all Zen cpus.

**Closed as completed** 2019-10-06 19:19 UTC
